import { getRoleDetail } from "@/lib/admin/roles";
import Forbidden from "@/components/Forbidden";
import RolesDetail from "@/components/admin/Roles/Detail";
// export const revalidate = 60;
export const metadata = {
  title: "Role Detail - Admin",
  description: "Generated by Next.js",
};
export default async function AdminRolesDetail({ params }) {
  const { id } = params;
  const { success, result } = await getRoleDetail(id);
  return (
    <>
      <div className="container-xxl flex-grow-1 container-p-y">
        <h4 className="fw-bold py-3 mb-4">
          <span className="text-muted fw-light">Roles /</span> Detail
        </h4>
        <div className="row">
          <div className="col-md-12">
            {success && success === 403 ? (
              <Forbidden />
            ) : (
              <RolesDetail role={result} />
            )}
          </div>
        </div>
      </div>
    </>
  );
}
