export const metadata = {
  title: "Settings - Admin",
  description: "Generated by Next.js",
};
export const revalidate = 0;
async function getListUser() {
  const users = [];
  if (!users) {
    throw new Error("Failed to fetch data");
  }
  return users;
}
export default async function AdminConfigs() {
  const users = await getListUser();
  return (
    <>
      <div className="container-xxl flex-grow-1 container-p-y">
        <div className="row">
          <h4 className="fw-bold py-3 mb-4">
            <span className="text-muted fw-light">Admin /</span> Settings
          </h4>
          <div className="row">
            <div className="col-md-12">
              <div className="card">
                <h5 className="card-header">List of User</h5>
                <div className="table-responsive text-nowrap">
                  <table className="table">
                    <thead>
                      <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Users</th>
                        <th>Status</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                    <tbody className="table-border-bottom-0">
                      {users &&
                        users.map((item) => {
                          return (
                            <tr key={item.id}>
                              <td>
                                <i className="fab fa-angular fa-lg text-danger me-3"></i>{" "}
                                <strong>{item.name}</strong>
                              </td>
                              <td>
                                <span>{item.email}</span>
                              </td>
                              <td>
                                <ul className="list-unstyled users-list m-0 avatar-group d-flex align-items-center">
                                  <li
                                    data-bs-toggle="tooltip"
                                    data-popup="tooltip-custom"
                                    data-bs-placement="top"
                                    className="avatar avatar-xs pull-up"
                                    title="Lilian Fuller"
                                  >
                                    <img
                                      src="/assets/admin/img/avatars/5.png"
                                      alt="Avatar"
                                      className="rounded-circle"
                                    />
                                  </li>
                                  <li
                                    data-bs-toggle="tooltip"
                                    data-popup="tooltip-custom"
                                    data-bs-placement="top"
                                    className="avatar avatar-xs pull-up"
                                    title="Sophia Wilkerson"
                                  >
                                    <img
                                      src="/assets/admin/img/avatars/6.png"
                                      alt="Avatar"
                                      className="rounded-circle"
                                    />
                                  </li>
                                  <li
                                    data-bs-toggle="tooltip"
                                    data-popup="tooltip-custom"
                                    data-bs-placement="top"
                                    className="avatar avatar-xs pull-up"
                                    title="Christina Parker"
                                  >
                                    <img
                                      src="/assets/admin/img/avatars/7.png"
                                      alt="Avatar"
                                      className="rounded-circle"
                                    />
                                  </li>
                                </ul>
                              </td>
                              <td>
                                <span className="badge bg-label-primary me-1">
                                  Active
                                </span>
                              </td>
                              <td>
                                <div className="dropdown">
                                  <button
                                    type="button"
                                    className="btn p-0 dropdown-toggle hide-arrow"
                                    data-bs-toggle="dropdown"
                                  >
                                    <i className="bx bx-dots-vertical-rounded"></i>
                                  </button>
                                  <div className="dropdown-menu">
                                    <a className="dropdown-item" href="">
                                      <i className="bx bx-edit-alt me-1"></i>{" "}
                                      Edit
                                    </a>
                                    <a className="dropdown-item" href="">
                                      <i className="bx bx-trash me-1"></i>{" "}
                                      Delete
                                    </a>
                                  </div>
                                </div>
                              </td>
                            </tr>
                          );
                        })}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
