export const metadata = {
  title: "Role - Admin",
  description: "Generated by Next.js",
};
import { getRoleList } from "@/lib/admin/roles";
import RolesIndex from "@/components/admin/Roles";
export default async function AdminRoles() {
  const data = await getRoleList();
  return (
    <>
      <div className="container-xxl flex-grow-1 container-p-y">
        <div className="row">
          <h4 className="fw-bold py-3 mb-4">
            <span className="text-muted fw-light">Admin /</span> Roles
          </h4>
          <div className="row">
            <div className="col-md-12">
              <div className="card">
                <h5 className="card-header">List of Roles</h5>
                <RolesIndex roles={data.result} />
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
