export const metadata = {
  title: "Permissions - Admin",
  description: "Generated by Next.js",
};
export default function AdminUserPermissions() {
  return (
    <>
      <div className="container-xxl flex-grow-1 container-p-y">
        <h1>Admin User Permissions</h1>
      </div>
    </>
  );
}
